### ISSUE TITLE
Differentiating blank line and Ctrl+C

### ISSUE THREAD

**Issue by sytelus** [yhirose/cpp-linenoise#2]
Is there any way to differentiate between whether user entered blank line or Ctrl+C. I currently don't see way in Realine() API. I think it would be nice to have a call back for Ctrl+C, Ctrl+Z etc.

**Comment by yhirose** [comment]
@sytelus, thanks for the report. This is actually a bug of the ReadLine interface. Sorry about that.
I am thinking to change the ReadLine interface to return std::shared_ptrstd::string instead of std::string, so that we could detect Ctrl+C as a null shared_ptr whereas an user blank line as a shared_ptr to an empty std::string.
What do you think?

**Comment by sytelus** [comment]
That would work as well however it will break interface for lot of folks. Another way to do it would be to add overloaded method with a ref parameters. Something like this:

`std::string Readline(const char *prompt, int& exitKeyCode, int& exitKeyFlags)`

This is slightly more verbose interface but has lot of advantage. Last two parameters tells you which keystroke caused Readline() to exit. It it was Enter then exitKeyCode = 13, exitKeyFlags = 0. if it was Ctrl+C then exitKeyCode = 'C' and exitKeyFlags = Ctrl. If I used Shift+Enter to complete the line then I can notice that too. In future, may be users can configure different keystrokes as exit keystrokes.

**Comment by yhirose** [comment]
Thanks for the suggestions. Using overloaded method idea sounds very good. I'll take the idea.
I'll add another `Readline` method to differentiate blank line and Ctrl-C. 

``` cpp
std::string Readline(const char *prompt, bool& quit)
```

When Ctrl-C is pressed, `quit` becomes `true`, otherwise (such as blank line) `false`.

When it comes to `exitKeyCode` and `exitKeyFlags`, it seems difficult to handle. If you took a look at the original linenoise code, you will see the linenoise receives a key code from the `read` system call. Unfortunately, It doesn't give us key status information...

**Comment by yhirose** [comment]
I have also added `bool Readline(const char *prompt, std::string& line)` that makes more sense.
